version: '3.8'

services:
  app:
    build:
      context: . # Usar el contexto actual (el directorio del proyecto)
      dockerfile: Dockerfile # Asegúrate de que este nombre sea correcto
    ports:
      - "2025:2025"  # Ajusta el puerto según sea necesario
    environment:
      - NODE_ENV=development # O development según tus necesidades